name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "0 2 * * 0-6"
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: carlazz/fast-gtfs-release:latest 
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: download dataset
      run: cd test_data/ && ./download_test_data.sh && cd -
    - name: Run tests
      run: cargo test --verbose
      env:
        HERE_APIKEY: ${{secrets.HERE_APIKEY}}
    - name: Upload release (if needed)
      run: test_data/do_release.sh ${{secrets.SECRET_API}}
